#!/bin/zsh
# Opt-in, platform-native E2E for the Espanso expansion loop.
#
# Verifies the real hot-reload → expand path: writes a Typvia-format config
# (byte-identical to what the app's compiler emits — guarded by the
# espanso-adapter compile tests and the compile_live check), lets the running
# espanso daemon pick it up, types the trigger into TextEdit, and asserts the
# expansion landed. Then it cleans up its file and closes the document.
#
# Requirements (why this is opt-in, like injector/panel live tests):
#   - macOS GUI session.
#   - espanso installed AND granted Accessibility permission (System Settings →
#     Privacy & Security → Accessibility). Without it, espanso cannot expand.
#   - The terminal running this script granted Accessibility too, to synthesize
#     the keystrokes via System Events.
#   - Not part of headless CI.
#
# Exit 0 = expansion observed; 1 = failure.
set -u

CONFIG_DIR="$HOME/Library/Application Support/espanso/match"
CONFIG_FILE="$CONFIG_DIR/typvia.yml"
TRIGGER=":typviaexpand"
SENTINEL="TYPVIA_EXPANDED_OK"

cleanup() {
  rm -f "$CONFIG_FILE"
  osascript -e 'tell application "TextEdit" to close (every document) saving no' >/dev/null 2>&1
}
trap cleanup EXIT

command -v espanso >/dev/null 2>&1 || { echo "espanso not installed"; exit 1; }

# Byte-for-byte the compiler's output for one immediate-mode trigger.
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<YAML
# Generated by Typvia. Do not edit — this file is regenerated from your snippets.
matches:
  - trigger: "$TRIGGER"
    replace: "$SENTINEL"
YAML

# Confirm espanso can see the trigger before driving the UI.
if ! espanso match list 2>/dev/null | grep -q "$TRIGGER"; then
  echo "espanso did not load the Typvia config (is it installed correctly?)"
  exit 1
fi

# Ensure the daemon is running and has the latest config (hot reload on write,
# restart to be deterministic).
if espanso service status 2>/dev/null | grep -qi "not running"; then
  espanso start >/dev/null 2>&1
else
  espanso restart >/dev/null 2>&1
fi
sleep 2
if ! espanso service status 2>/dev/null | grep -qi "is running"; then
  echo "espanso service is not running — grant Accessibility permission and retry"
  exit 1
fi

# Type the trigger into a fresh TextEdit document.
osascript <<'APPLESCRIPT'
tell application "TextEdit"
  activate
  make new document
end tell
delay 0.6
tell application "System Events"
  keystroke ":typviaexpand "
end tell
APPLESCRIPT
sleep 1.5

DOC_TEXT=$(osascript -e 'tell application "TextEdit" to get text of front document' 2>/dev/null)

if print -r -- "$DOC_TEXT" | grep -q "$SENTINEL"; then
  if print -r -- "$DOC_TEXT" | grep -q "$TRIGGER"; then
    echo "FAIL: trigger text remained un-expanded: $DOC_TEXT"
    exit 1
  fi
  echo "PASS: '$TRIGGER' expanded to '$SENTINEL' in TextEdit"
  exit 0
fi

echo "FAIL: expansion not observed. Document was: $DOC_TEXT"
exit 1
