#!/usr/bin/env bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

# Reproducible Android FFI build: compiles the typvia-mobile-ffi shared
# library for the two required Android ABIs (arm64-v8a device + x86_64
# emulator, min API 28), generates the Kotlin bindings in library mode (no
# UDL), lays the .so files out in the jniLibs/ convention the IME module
# consumes, and runs
# the host Kotlin smoke against the same generated bindings.
#
# Outputs land in target/mobile-ffi-android/ (build products, never
# committed). Toolchain wiring is explicit env per target (cargo linker +
# cc/ar for rusqlite's bundled SQLite); no cargo-ndk or other tooling.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$ROOT/target/mobile-ffi-android"
GEN="$OUT/generated"
LIB=libtypvia_mobile_ffi

# The product's minSdk baseline; the clang wrappers encode the API level.
API=28
NDK="${ANDROID_NDK_HOME:-$HOME/zh/SDK/Android/ndk/27.0.12077973}"
# NDK r23+ ships one host prebuilt dir (darwin-x86_64 holds universal
# binaries on Apple silicon); resolve it instead of hardcoding the name.
TOOLCHAIN=""
for dir in "$NDK"/toolchains/llvm/prebuilt/*/bin; do
  [[ -x "$dir/aarch64-linux-android$API-clang" ]] && TOOLCHAIN="$dir" && break
done
if [[ -z "$TOOLCHAIN" ]]; then
  echo "error: no NDK toolchain with API $API clang under $NDK" >&2
  echo "       set ANDROID_NDK_HOME to an NDK install (r26+)" >&2
  exit 1
fi

# The smoke's Gradle wrapper needs JDK 17 (same baseline as gen/android).
export JAVA_HOME="${JAVA_HOME:-/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home}"

cd "$ROOT"

echo "==> Building Android shared libraries (release, API $API)"
export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$TOOLCHAIN/aarch64-linux-android$API-clang"
export CC_aarch64_linux_android="$TOOLCHAIN/aarch64-linux-android$API-clang"
export AR_aarch64_linux_android="$TOOLCHAIN/llvm-ar"
export CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER="$TOOLCHAIN/x86_64-linux-android$API-clang"
export CC_x86_64_linux_android="$TOOLCHAIN/x86_64-linux-android$API-clang"
export AR_x86_64_linux_android="$TOOLCHAIN/llvm-ar"
cargo build -p typvia-mobile-ffi --release --target aarch64-linux-android
cargo build -p typvia-mobile-ffi --release --target x86_64-linux-android

echo "==> Building host library (bindgen metadata + smoke load)"
cargo build -p typvia-mobile-ffi --release

rm -rf "$OUT"
mkdir -p "$GEN" "$OUT/jniLibs/arm64-v8a" "$OUT/jniLibs/x86_64"

echo "==> Generating Kotlin bindings (library mode)"
# The host cdylib carries the build host's extension: .dylib on a macOS
# workstation, .so on a Linux CI runner.
HOST_LIB="$ROOT/target/release/$LIB.dylib"
[[ -f "$HOST_LIB" ]] || HOST_LIB="$ROOT/target/release/$LIB.so"
cargo run -p typvia-mobile-ffi --bin uniffi-bindgen --features uniffi/cli --release -- \
  generate --library "$HOST_LIB" \
  --language kotlin --out-dir "$GEN"

# jniLibs layout matches the Android packaging convention (ABI dir names,
# not rust target triples), so the IME module can point at it directly.
cp "$ROOT/target/aarch64-linux-android/release/$LIB.so" "$OUT/jniLibs/arm64-v8a/$LIB.so"
cp "$ROOT/target/x86_64-linux-android/release/$LIB.so" "$OUT/jniLibs/x86_64/$LIB.so"

echo "==> Host Kotlin smoke (typed calls through the generated bindings)"
# Throwaway Gradle JVM project: compiles the generated bindings plus the
# committed smoke source and runs them on the host JVM, JNA loading the
# host dylib. JNA is the binding's only runtime dependency — this surface
# exports no async functions, so kotlinx-coroutines is never pulled in.
# Reuses the repo's existing Gradle wrapper (gen/android) via -p; no
# system-wide Kotlin or Gradle install required.
SMOKE="$OUT/smoke-host"
mkdir -p "$SMOKE/src/main/kotlin"
cp -R "$GEN/uniffi" "$SMOKE/src/main/kotlin/"
cp "$ROOT/crates/mobile-ffi/smoke/Main.kt" "$SMOKE/src/main/kotlin/Main.kt"

cat > "$SMOKE/settings.gradle.kts" <<'EOF'
// Generated by build-android.sh (throwaway smoke runner, never committed).
rootProject.name = "typvia-ffi-smoke"
EOF

cat > "$SMOKE/build.gradle.kts" <<EOF
// Generated by build-android.sh (throwaway smoke runner, never committed).
plugins {
    kotlin("jvm") version "2.1.20"
    application
}

repositories {
    mavenCentral()
}

dependencies {
    // Required at runtime by UniFFI-generated Kotlin; Apache-2.0 under its
    // Apache-2.0/LGPL-2.1 dual license (MPL-2.0 compatible).
    implementation("net.java.dev.jna:jna:5.17.0")
}

application {
    mainClass.set("MainKt")
}

tasks.named<JavaExec>("run") {
    // The host smoke loads the host dylib, not the Android .so files.
    systemProperty("jna.library.path", "$ROOT/target/release")
}
EOF

# Skipped when the Android build is the caller: it compiles these same
# bindings a few tasks later, which is the stronger check, and a Gradle build
# that starts another Gradle build inside itself is a slow way to learn that.
if [[ "${TYPVIA_FFI_SMOKE:-run}" == "skip" ]]; then
  echo "==> Kotlin smoke skipped (the caller compiles these bindings itself)"
else
  # The native Android app brings its own wrapper, so the smoke uses that
  # rather than requiring a Gradle install; a plain `gradle` still works for
  # anyone who has one.
  WRAPPER="$ROOT/apps/android/gradlew"
  if [[ -x "$WRAPPER" ]]; then
    GRADLE=("$WRAPPER")
  elif command -v gradle >/dev/null; then
    GRADLE=(gradle)
  else
    echo "error: no Gradle wrapper at apps/android/gradlew and none on PATH," >&2
    echo "       so the Kotlin smoke cannot run; the .so files and bindings" >&2
    echo "       above are built, the smoke is not" >&2
    exit 1
  fi
  "${GRADLE[@]}" -p "$SMOKE" --no-daemon --console=plain -q run
fi

echo "==> Done: $OUT/jniLibs (arm64-v8a + x86_64), bindings in $GEN"
